In [1]:
import pandas as pd
import numpy as np

In [2]:
stats = pd.read_pickle('C:/Users/YAVUZ/Transfer Fee Project/Stats_Scraper/matches_win_lose2.pkl')

In [3]:
pos_groups = pd.read_csv('./position_group.csv', delimiter=";")
pos_groups.columns = ['Pos.', 'Excuse']

In [4]:
stats['Pos.'] = stats['Pos.'].str.replace('\xa0','')
stats = stats.merge(pos_groups, on=['Pos.'], how='left')

In [5]:
stats.head()

,Matchday,Date,Home_Team,Home team,Away_Team,Away team,Result,Pos.,Goals,Assists,...,Transfer_Date,Team_Left,Team_Joined,Team,Start,End,Home_Goals,Away_Goals,Win_Draw_Lose,Excuse
0,\n\n\t\t\t\t\t\t\t\t\t\t\t1,2013-08-10,FC Augsburg,FC Augsburg (8.),Borussia Dortmund,Bor. Dortmund (2.),0:4,LW,,1,...,2016-01-01,Borussia Dortmund,Borussia Mönchengladbach,Borussia Dortmund,2013-07-01,2014-09-01,0,4,win,Position
1,\n\n\t\t\t\t\t\t\t\t\t\t\t2,2013-08-18,Borussia Dortmund,Bor. Dortmund (2.),Eintracht Braunschweig,E. Braunschweig (13.),2:1,RW,1,1,...,2016-01-01,Borussia Dortmund,Borussia Mönchengladbach,Borussia Dortmund,2013-07-01,2014-09-01,2,1,win,Position
2,\n\n\t\t\t\t\t\t\t\t\t\t\t3,2013-08-23,Borussia Dortmund,Bor. Dortmund (1.),SV Werder Bremen,Werder Bremen (5.),1:0,LW,,,...,2016-01-01,Borussia Dortmund,Borussia Mönchengladbach,Borussia Dortmund,2013-07-01,2014-09-01,1,0,win,Position
3,\n\n\t\t\t\t\t\t\t\t\t\t\t4,2013-09-01,Eintracht Frankfurt,E. Frankfurt (11.),Borussia Dortmund,Bor. Dortmund (1.),1:2,on the bench,NaN,NaN,...,2016-01-01,Borussia Dortmund,Borussia Mönchengladbach,Borussia Dortmund,2013-07-01,2014-09-01,1,2,win,on the bench
4,\n\n\t\t\t\t\t\t\t\t\t\t\t5,2013-09-14,Borussia Dortmund,Bor. Dortmund (1.),Hamburger SV,Hamburger SV (12.),6:2,LW,,,...,2016-01-01,Borussia Dortmund,Borussia Mönchengladbach,Borussia Dortmund,2013-07-01,2014-09-01,6,2,win,Position

In [6]:
#transfer id içerisinde gelen maç sayısı
stats.sort_values(by=['Transfer_id','Date'],ascending=False, inplace=True)
stats['match_count'] = stats.groupby('Transfer_id').cumcount()

In [7]:
stats.columns

Index(['Matchday', 'Date', 'Home_Team', 'Home team', 'Away_Team', 'Away team',
       'Result', 'Pos.', 'Goals', 'Assists', 'Own goals', 'Yellow cards',
       'Second yellow cards', 'Red cards', 'Substitutions on',
       'Substitutions off', 'Transfermarkt Player Rating', 'Minutes played',
       'Competition', 'Stats_Season', 'Transfer_Link', 'Transfer_id', 'id',
       'Transfer_Date', 'Team_Left', 'Team_Joined', 'Team', 'Start', 'End',
       'Home_Goals', 'Away_Goals', 'Win_Draw_Lose', 'Excuse', 'match_count'],
      dtype='object')

In [8]:
#kolonları numerik yapma
stats['Minutes played'] = pd.to_numeric(stats['Minutes played'].str.replace('\'',''),  errors='coerce')
stats['Substitutions on'] = pd.to_numeric(stats['Substitutions on'].str.replace('\'',''),  errors='coerce')
stats['Substitutions off'] = pd.to_numeric(stats['Substitutions off'].str.replace('\'',''),  errors='coerce')
stats['Goals'] = pd.to_numeric(stats['Goals'], errors='coerce')
stats['Assists'] = pd.to_numeric(stats['Assists'], errors='coerce')
stats['Own goals'] = pd.to_numeric(stats['Own goals'], errors='coerce')
stats['Yellow cards'] = pd.to_numeric(stats['Yellow cards'].str.replace('\'',''), errors='coerce')
stats['Second yellow cards'] = pd.to_numeric(stats['Second yellow cards'].str.replace('\'',''), errors='coerce')
stats['Red cards'] = pd.to_numeric(stats['Red cards'].str.replace('\'',''), errors='coerce')
stats['Home_Goals'] = pd.to_numeric(stats['Home_Goals'], errors='coerce')
stats['Away_Goals'] = pd.to_numeric(stats['Away_Goals'], errors='coerce')

In [9]:
conditions = [stats['Yellow cards']>=0]
output = [1]
stats['yellow_card_flag'] = np.select(conditions, output, default=0)

In [10]:
conditions = [stats['Second yellow cards']>=0]
output = [1]
stats['second_yellow_card_flag'] = np.select(conditions, output, default=0)

In [11]:
conditions = [stats['Red cards']>=0]
output = [1]
stats['red_card_flag'] = np.select(conditions, output, default=0)

In [12]:
#maçta oynadı mı
conditions = [stats['Minutes played']>0]
output = [1]
stats['matches_played_flag'] = np.select(conditions, output, default=0)
stats.head()

,Matchday,Date,Home_Team,Home team,Away_Team,Away team,Result,Pos.,Goals,Assists,...,End,Home_Goals,Away_Goals,Win_Draw_Lose,Excuse,match_count,yellow_card_flag,second_yellow_card_flag,red_card_flag,matches_played_flag
1025631,\n\n\t\t\t\t\t\t\t\t\t\t\t30,2020-09-09,Al-Nassr FC,Al-Nassr,Al-Ettifaq,Al-Ettifaq,3:2,not in squad,NaN,NaN,...,2020-10-16,3,2,lose,not in squad,0,0,0,0,0
1025630,\n\n\t\t\t\t\t\t\t\t\t\t\t29,2020-09-04,Al-Ettifaq,Al-Ettifaq,Damac FC,Damac FC,0:2,not in squad,NaN,NaN,...,2020-10-16,0,2,lose,not in squad,1,0,0,0,0
1025629,\n\n\t\t\t\t\t\t\t\t\t\t\t28,2020-08-30,Al-Taawon,Taawon,Al-Ettifaq,Al-Ettifaq,0:1,not in squad,NaN,NaN,...,2020-10-16,0,1,win,not in squad,2,0,0,0,0
1025628,\n\n\t\t\t\t\t\t\t\t\t\t\t27,2020-08-24,Al-Ettifaq,Al-Ettifaq (8.),Al-Raed,Al-Raed (6.),4:0,not in squad,NaN,NaN,...,2020-10-16,4,0,win,not in squad,3,0,0,0,0
1025627,\n\n\t\t\t\t\t\t\t\t\t\t\t26,2020-08-19,Al-Fateh,Al-Fateh (13.),Al-Ettifaq,Al-Ettifaq (8.),1:1,not in squad,NaN,NaN,...,2020-10-16,1,1,draw,not in squad,4,0,0,0,0

In [13]:
#maça ilk11 başladı mı
conditions = [(stats['Substitutions on'].isna())&(stats['Minutes played']>0)]
output = [1]
stats['starting_lineup'] = np.select(conditions, output, default=0)
stats.loc[stats['Minutes played']>0,['Transfer_id','Substitutions on', 'Substitutions off','Minutes played','starting_lineup']].head(20)

,Transfer_id,Substitutions on,Substitutions off,Minutes played,starting_lineup
1025623,3105419,86.0,NaN,4.0,0
1025622,3105419,66.0,NaN,24.0,0
1025619,3105419,NaN,46.0,45.0,1
1025617,3105419,NaN,69.0,69.0,1
1025616,3105419,59.0,NaN,31.0,0
1025635,3105419,78.0,NaN,42.0,0
1025615,3105419,74.0,NaN,16.0,0
1025612,3105419,NaN,NaN,90.0,1
1025633,3105419,NaN,NaN,90.0,1
1025611,3105419,NaN,84.0,84.0,1
1025632,3105419,NaN,69.0,69.0,1
1025610,3105419,70.0,NaN,20.0,0
1025609,3105419,74.0,NaN,16.0,0
1025608,3105419,55.0,NaN,35.0,0
1025607,3105419,NaN,71.0,71.0,1
1025606,3105419,NaN,87.0,87.0,1
1025605,3105419,60.0,NaN,30.0,0
1025604,3105419,NaN,73.0,73.0,1
1025602,3105419,NaN,66.0,66.0,1
1026152,3105139,NaN,NaN,23.0,1

In [14]:
#oyundan alındı mı
conditions = [stats['Substitutions off']>0]
output = [1]
stats['substitution_off_flag'] = np.select(conditions, output, default=0)
stats.loc[stats['Minutes played']>0,['Transfer_id','Substitutions on', 'Substitutions off','Minutes played','substitution_off_flag']].head(20)

,Transfer_id,Substitutions on,Substitutions off,Minutes played,substitution_off_flag
1025623,3105419,86.0,NaN,4.0,0
1025622,3105419,66.0,NaN,24.0,0
1025619,3105419,NaN,46.0,45.0,1
1025617,3105419,NaN,69.0,69.0,1
1025616,3105419,59.0,NaN,31.0,0
1025635,3105419,78.0,NaN,42.0,0
1025615,3105419,74.0,NaN,16.0,0
1025612,3105419,NaN,NaN,90.0,0
1025633,3105419,NaN,NaN,90.0,0
1025611,3105419,NaN,84.0,84.0,1
1025632,3105419,NaN,69.0,69.0,1
1025610,3105419,70.0,NaN,20.0,0
1025609,3105419,74.0,NaN,16.0,0
1025608,3105419,55.0,NaN,35.0,0
1025607,3105419,NaN,71.0,71.0,1
1025606,3105419,NaN,87.0,87.0,1
1025605,3105419,60.0,NaN,30.0,0
1025604,3105419,NaN,73.0,73.0,1
1025602,3105419,NaN,66.0,66.0,1
1026152,3105139,NaN,NaN,23.0,0

In [15]:
len(stats['Transfer_id'].unique())

9381

In [16]:
def stats_features(count):
    unique_transfers = stats['Transfer_id'].unique()
    base_df = pd.DataFrame(unique_transfers, columns =['Transfer_id']).set_index('Transfer_id')
    lastx = stats[stats['match_count']<count]
    match_count = lastx[['Transfer_id','Date']].groupby('Transfer_id').count()
    base_df = base_df.merge(match_count, on='Transfer_id', how = 'left')
    rate_start_lineup = lastx[['Transfer_id','starting_lineup']].groupby('Transfer_id').sum()
    base_df = base_df.merge(rate_start_lineup, left_index=True, right_index=True, how='left')
    games_played = lastx[['Transfer_id','matches_played_flag']].groupby('Transfer_id').sum()
    base_df = base_df.merge(games_played, left_index=True, right_index=True, how='left')
    cols = ['Transfer_id','Goals', 'Assists', 'Own goals', 'yellow_card_flag',
       'second_yellow_card_flag', 'red_card_flag', 'Minutes played','substitution_off_flag']
    lastx_stats =lastx[cols].groupby('Transfer_id').aggregate({'Goals':'sum', 'Assists':'sum', 'Own goals':'sum',\
            'yellow_card_flag':'sum', 'second_yellow_card_flag':'sum','red_card_flag':'sum',\
            'Minutes played':'sum','substitution_off_flag':'sum'})
    base_df = base_df.merge(lastx_stats, left_index=True, right_index=True, how='left')
    base_df['match_played_rate'] = round(base_df['matches_played_flag'] / base_df['Date'], 2)

    
    
    
    
    
    base_df['rate_subs_off'] = round(base_df['substitution_off_flag'] / base_df['starting_lineup'], 2)
    conditions = [lastx['Win_Draw_Lose'] =='win',lastx['Win_Draw_Lose'] =='draw']
    outputs = [3,1]
    lastx['match_points'] = np.select(conditions, outputs, default=0)
    total_points_played = lastx.loc[lastx['matches_played_flag']==1,['Transfer_id','match_points']].groupby('Transfer_id').sum().add_suffix('_played')
    total_points_notplayed = lastx.loc[lastx['matches_played_flag']==0,['Transfer_id','match_points']].groupby('Transfer_id').sum().add_suffix('_notplayed')
    base_df = base_df.merge(total_points_played, left_index = True, right_index=True, how='left')
    base_df = base_df.merge(total_points_notplayed, left_index = True, right_index=True, how='left')
    team_away_goals = lastx.loc[lastx['Team'] == lastx['Away_Team'],['Transfer_id','Away_Goals']].groupby('Transfer_id').sum().add_suffix('_team')
    team_home_goals = lastx.loc[lastx['Team'] == lastx['Home_Team'],['Transfer_id','Home_Goals']].groupby('Transfer_id').sum().add_suffix('_team')
    team_away_goals_played = lastx.loc[(lastx['Team'] == lastx['Away_Team'])&(lastx['matches_played_flag']==1),['Transfer_id','Away_Goals']].groupby('Transfer_id').sum().add_suffix('_team_played')
    team_home_goals_played = lastx.loc[(lastx['Team'] == lastx['Home_Team'])&(lastx['matches_played_flag']==1),['Transfer_id','Home_Goals']].groupby('Transfer_id').sum().add_suffix('_team_played')  
    base_df = base_df.merge(team_home_goals, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(team_away_goals, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(team_home_goals_played, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(team_away_goals_played, left_index=True, right_index=True, how='left')
    base_df['total_goals_team'] = base_df['Home_Goals_team'] + base_df['Away_Goals_team']
    base_df['total_goals_team_played'] = base_df['Home_Goals_team_played'] + base_df['Away_Goals_team_played']
    team_away_conceded_goals = lastx.loc[lastx['Team'] == lastx['Home_Team'],['Transfer_id','Away_Goals']].groupby('Transfer_id').sum().add_suffix('_team_conceded')
    team_home_conceded_goals = lastx.loc[lastx['Team'] == lastx['Away_Team'],['Transfer_id','Home_Goals']].groupby('Transfer_id').sum().add_suffix('_team_conceded')
    team_away_conceded_goals_played = lastx.loc[(lastx['Team'] == lastx['Home_Team'])&(lastx['matches_played_flag']==1),['Transfer_id','Away_Goals']].groupby('Transfer_id').sum().add_suffix('_team_conceded_played')
    team_home_conceded_goals_played = lastx.loc[(lastx['Team'] == lastx['Away_Team'])&(lastx['matches_played_flag']==1),['Transfer_id','Home_Goals']].groupby('Transfer_id').sum().add_suffix('_team_conceded_played')
    base_df = base_df.merge(team_away_conceded_goals, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(team_home_conceded_goals, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(team_away_conceded_goals_played, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(team_home_conceded_goals_played, left_index=True, right_index=True, how='left')
    base_df['total_goals_team_conceded'] = base_df['Home_Goals_team_conceded'] + base_df['Away_Goals_team_conceded']
    base_df['total_goals_team_conceded_played'] = base_df['Home_Goals_team_conceded_played'] + base_df['Away_Goals_team_conceded_played']
    

    conditions = [((lastx['Team'] == lastx['Home_Team']) & (lastx['Away_Goals']==0)) , ((lastx['Team'] == lastx['Away_Team']) & (lastx['Home_Goals']==0)) ]
    outputs = [1,1]
    lastx['clean_sheet_flg'] = np.select(conditions, outputs, default=0)    
    total_clean_sheets_played=lastx.loc[lastx['matches_played_flag']==1,['Transfer_id','clean_sheet_flg']].groupby('Transfer_id').sum().add_suffix('_played')
    total_clean_sheets_not_played=lastx.loc[lastx['matches_played_flag']==0,['Transfer_id','clean_sheet_flg']].groupby('Transfer_id').sum().add_suffix('_notplayed')
    base_df = base_df.merge(total_clean_sheets_played, left_index=True, right_index=True, how='left')
    base_df = base_df.merge(total_clean_sheets_not_played, left_index=True, right_index=True, how='left')
    
    
    #Played per game Features
    base_df['lineup_rate'] = round(base_df['starting_lineup'] / base_df['matches_played_flag'], 2)
    base_df['minutes_per_game'] = round(base_df['Minutes played'] / base_df['matches_played_flag'],2)
    
    base_df['goals_per_Game'] = round(base_df['Goals'] / base_df['matches_played_flag'],2)
    
    base_df['assists_per_game'] = round(base_df['Assists'] / base_df['matches_played_flag'],2)
    
    base_df['own_goals_per_game'] = round(base_df['Own goals'] / base_df['matches_played_flag'],2)
    
    base_df['yellow_cards_per_game'] = round(base_df['yellow_card_flag'] / base_df['matches_played_flag'],2)
    
    base_df['second_yellow_card_per_game'] = round(base_df['second_yellow_card_flag'] / base_df['matches_played_flag'],2)
    
    base_df['red_card_per_game'] = round(base_df['red_card_flag'] / base_df['matches_played_flag'],2)
    
    base_df['team_goals_per_game'] = round(base_df['total_goals_team_played'] / base_df['matches_played_flag'],2)
    
    base_df['points_per_game'] = round(base_df['match_points_played'] / base_df['matches_played_flag'],2)
    
    base_df['team_conceeded_goals_per_game'] = round(base_df['total_goals_team_conceded_played'] / base_df['matches_played_flag'],2)
    
    base_df['clean_sheet_per_game'] = round(base_df['clean_sheet_flg_played'] / base_df['matches_played_flag'],2)
    
    
    #Not Played per game Features
    base_df['team_goals_per_game_not_played'] = round((base_df['total_goals_team'] - base_df['total_goals_team_played'])/(base_df['Date']-base_df['matches_played_flag']),2)
    
    base_df['clean_sheet_per_game_not_played'] = round(base_df['clean_sheet_flg_notplayed'] / (base_df['Date']-base_df['matches_played_flag']),2)
    
    base_df['team_conceeded_goals_per_game_not_played'] = round((base_df['total_goals_team_conceded'] - base_df['total_goals_team_conceded_played'])/(base_df['Date']-base_df['matches_played_flag']),2)
    base_df['points_per_game_not_played'] = round(base_df['match_points_notplayed']/(base_df['Date']-base_df['matches_played_flag']),2)
    
    #Coverage Features
    base_df['minutes_played_coverage_played'] =round(base_df['Minutes played']/(90*base_df['matches_played_flag']),2)
    base_df['minutes_played_coverage_all'] =round(base_df['Minutes played']/(90*base_df['Date']),2)    
    base_df['points_played_coverage'] = round(base_df['match_points_played'] / (3*base_df['matches_played_flag']),2)   
    base_df['points_not_played_coverage'] = round(base_df['match_points_notplayed'] / (3*(base_df['Date']-base_df['matches_played_flag'])),2)
    
    
    #Injury/Suspenion/bench/not in squad rate
    pos_count = lastx[['Transfer_id','Excuse','Date']].groupby(['Transfer_id','Excuse']).count().reset_index()
    pos_count_transpose = pd.pivot_table(pos_count, values = 'Date', index=['Transfer_id'], columns = 'Excuse').reset_index()
    pos_count_final = pos_count_transpose[['Transfer_id','Injury','Suspension','not in squad','on the bench ']]
    pos_count_final = pos_count_final.reset_index(drop=True).set_index('Transfer_id')
    base_df = base_df.merge(pos_count_final, left_index=True, right_index=True,how='left')
    
    base_df['injury_rate'] = round(base_df['Injury']/base_df['Date'],2)
    
    base_df['suspension_rate'] = round(base_df['Suspension']/base_df['Date'],2)
    
    base_df['on_the_bench_rate'] = round(base_df['on the bench ']/base_df['Date'],2)
    
    base_df['not_in_squad_rate'] = round(base_df['not in squad']/base_df['Date'],2)
    
    #Min_date/recency
    transfer_date=lastx[['Transfer_id','Transfer_Date']].drop_duplicates().set_index('Transfer_id')
    base_df = base_df.merge(transfer_date, left_index=True, right_index=True,how='left')
    min_date=lastx[['Transfer_id','Date']].groupby('Transfer_id').min().add_suffix('_min')
    base_df = base_df.merge(min_date, left_index=True, right_index=True,how='left')
    base_df['last_played_game_recency']=base_df['Transfer_Date']-base_df['Date_min']
    
    
    #drop unnecessary columns
    
    base_df.drop(['Transfer_Date', 'Date_min','Away_Goals_team_conceded','Home_Goals_team_conceded', 'Away_Goals_team_conceded_played','Home_Goals_team_conceded_played','Home_Goals_team', 'Away_Goals_team','Home_Goals_team_played', 'Away_Goals_team_played'], axis=1, inplace=True)
    base_df=base_df.add_suffix('_'+str(count))
    return base_df

In [17]:
stats_features_30=stats_features(30)

<ipython-input-16-ed8420bc1147>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['match_points'] = np.select(conditions, outputs, default=0)
<ipython-input-16-ed8420bc1147>:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['clean_sheet_flg'] = np.select(conditions, outputs, default=0)

In [18]:
stats_features_20=stats_features(20)

<ipython-input-16-ed8420bc1147>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['match_points'] = np.select(conditions, outputs, default=0)
<ipython-input-16-ed8420bc1147>:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['clean_sheet_flg'] = np.select(conditions, outputs, default=0)

In [19]:
stats_features_10=stats_features(10)

<ipython-input-16-ed8420bc1147>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['match_points'] = np.select(conditions, outputs, default=0)
<ipython-input-16-ed8420bc1147>:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['clean_sheet_flg'] = np.select(conditions, outputs, default=0)

In [20]:
stats_features_5=stats_features(5)

<ipython-input-16-ed8420bc1147>:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['match_points'] = np.select(conditions, outputs, default=0)
<ipython-input-16-ed8420bc1147>:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastx['clean_sheet_flg'] = np.select(conditions, outputs, default=0)

In [21]:
stats_features_5

,Date_5,starting_lineup_5,matches_played_flag_5,Goals_5,Assists_5,Own goals_5,yellow_card_flag_5,second_yellow_card_flag_5,red_card_flag_5,Minutes played_5,...,points_not_played_coverage_5,Injury_5,Suspension_5,not in squad_5,on the bench _5,injury_rate_5,suspension_rate_5,on_the_bench_rate_5,not_in_squad_rate_5,last_played_game_recency_5
Transfer_id,,,,,,,,,,,,,,,,,,,,,
3105419,5,0,0,0.0,0.0,0.0,0,0,0,0.0,...,0.47,NaN,NaN,5.0,NaN,NaN,NaN,NaN,1.0,58 days
3105139,5,4,4,5.0,5.0,0.0,0,0,0,284.0,...,0.00,NaN,NaN,1.0,NaN,NaN,NaN,NaN,0.2,255 days
3105032,5,4,4,1.0,0.0,0.0,0,0,0,337.0,...,0.00,NaN,NaN,NaN,1.0,NaN,NaN,0.2,NaN,339 days
3104833,5,5,5,2.0,0.0,0.0,0,0,0,450.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100 days
3104831,5,0,0,0.0,0.0,0.0,0,0,0,0.0,...,0.67,4.0,NaN,NaN,NaN,0.8,NaN,NaN,NaN,90 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1264780,5,5,5,0.0,1.0,0.0,2,0,0,450.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72 days
1251886,5,3,4,0.0,0.0,0.0,0,0,0,286.0,...,0.00,NaN,NaN,NaN,1.0,NaN,NaN,0.2,NaN,68 days
1194818,5,5,5,1.0,0.0,0.0,1,0,0,400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,78 days
1183078,5,0,0,0.0,0.0,0.0,0,0,0,0.0,...,0.27,NaN,NaN,2.0,3.0,NaN,NaN,0.6,0.4,72 days
1115385,5,5,5,0.0,0.0,0.0,3,0,0,431.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72 days

In [44]:
from functools import reduce
data_frames = [stats_features_30,stats_features_20, stats_features_10, stats_features_5]
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Transfer_id'],
                                            how='outer'), data_frames)

In [46]:
df_merged.to_pickle('./Stats_Features_All.pkl')